# Generated by Django 6.0.4 on 2026-04-20 02:33

import base_feature_app.models.order
import django.core.validators
import django.db.models.deletion
import django_attachments.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_feature_app', '0004_passwordcode'),
        ('django_attachments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GlobalColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('slug', models.SlugField(unique=True)),
                ('hex_code', models.CharField(max_length=7)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GlobalSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30)),
                ('slug', models.SlugField(unique=True)),
                ('cm', models.CharField(max_length=10)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(default=base_feature_app.models.order._generate_order_number, max_length=30, unique=True)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('pending_payment', 'Pendiente de pago'), ('payment_confirmed', 'Pago confirmado'), ('in_production', 'En producción'), ('shipped', 'Despachado'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado')], default='pending_payment', max_length=20)),
                ('total_amount', models.PositiveIntegerField()),
                ('deposit_amount', models.PositiveIntegerField()),
                ('balance_amount', models.PositiveIntegerField()),
                ('tracking_number', models.CharField(blank=True, max_length=100)),
                ('shipping_carrier', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('last_automated_email_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_status_changes', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='base_feature_app.order')),
            ],
            options={
                'verbose_name_plural': 'order status histories',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Peluch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('lead_description', models.CharField(max_length=280)),
                ('description', models.TextField()),
                ('specifications', models.JSONField(default=dict)),
                ('care_instructions', models.JSONField(default=list)),
                ('badge', models.CharField(choices=[('none', 'Sin badge'), ('bestseller', 'Más vendido'), ('new', 'Nuevo'), ('limited_edition', 'Edición limitada')], default='none', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('has_huella', models.BooleanField(default=False)),
                ('has_corazon', models.BooleanField(default=False)),
                ('has_audio', models.BooleanField(default=False)),
                ('huella_extra_cost', models.PositiveIntegerField(default=0)),
                ('corazon_extra_cost', models.PositiveIntegerField(default=0)),
                ('audio_extra_cost', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('available_colors', models.ManyToManyField(blank=True, related_name='peluches', to='base_feature_app.globalcolor')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='peluches', to='base_feature_app.category')),
                ('gallery', django_attachments.fields.GalleryField(on_delete=django.db.models.deletion.CASCADE, related_name='peluches_with_gallery', to='django_attachments.library')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_path', models.CharField(max_length=255)),
                ('session_id', models.CharField(max_length=64)),
                ('is_new_visitor', models.BooleanField(default=True)),
                ('device_type', models.CharField(choices=[('mobile', 'Móvil'), ('tablet', 'Tablet'), ('desktop', 'Escritorio')], default='mobile', max_length=10)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('traffic_source', models.CharField(choices=[('instagram', 'Instagram'), ('google', 'Google'), ('whatsapp', 'WhatsApp'), ('direct', 'Directo'), ('other', 'Otro')], default='direct', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_views', to=settings.AUTH_USER_MODEL)),
                ('peluch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_views', to='base_feature_app.peluch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonalizationMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('huella_image', 'Imagen de huella'), ('audio', 'Audio personalizado')], max_length=20)),
                ('file', models.FileField(upload_to='personalizations/%Y/%m/')),
                ('file_size_kb', models.PositiveIntegerField()),
                ('duration_sec', models.FloatField(blank=True, null=True)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personalization_media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('unit_price', models.PositiveIntegerField()),
                ('has_huella', models.BooleanField(default=False)),
                ('huella_type', models.CharField(blank=True, choices=[('name', 'Nombre'), ('date', 'Fecha'), ('letter', 'Letra'), ('image', 'Imagen')], max_length=10)),
                ('huella_text', models.CharField(blank=True, max_length=60)),
                ('has_corazon', models.BooleanField(default=False)),
                ('corazon_phrase', models.CharField(blank=True, max_length=50)),
                ('has_audio', models.BooleanField(default=False)),
                ('personalization_cost', models.PositiveIntegerField(default=0)),
                ('configuration_snapshot', models.JSONField(default=dict)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='base_feature_app.globalcolor')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='base_feature_app.order')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='base_feature_app.globalsize')),
                ('peluch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='base_feature_app.peluch')),
                ('audio_media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audio_items', to='base_feature_app.personalizationmedia')),
                ('huella_media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='huella_items', to='base_feature_app.personalizationmedia')),
            ],
        ),
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('faq', 'Preguntas frecuentes'), ('history', 'Historia de Peluchelandia'), ('terms', 'Términos y condiciones'), ('welcome_text', 'Texto de bienvenida'), ('contact_info', 'Información de contacto')], max_length=30, unique=True)),
                ('content_json', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_content_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'site content',
            },
        ),
        migrations.CreateModel(
            name='WompiTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wompi_id', models.CharField(blank=True, max_length=200)),
                ('reference', models.CharField(max_length=200, unique=True)),
                ('amount_in_cents', models.PositiveIntegerField()),
                ('currency', models.CharField(default='COP', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('declined', 'Rechazado'), ('voided', 'Anulado'), ('error', 'Error')], default='pending', max_length=10)),
                ('payment_method_type', models.CharField(blank=True, max_length=50)),
                ('checkout_url', models.URLField(blank=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='base_feature_app.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PeluchSizePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('peluch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_prices', to='base_feature_app.peluch')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='peluch_prices', to='base_feature_app.globalsize')),
            ],
            options={
                'ordering': ['size__sort_order'],
                'unique_together': {('peluch', 'size')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='base_feature_app.order')),
                ('peluch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='base_feature_app.peluch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('peluch', 'user')},
            },
        ),
    ]
