# Generated by Django 6.0.4 on 2026-04-22 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_feature_app', '0006_peluch_description_to_json'),
        ('django_attachments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeluchColorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_attachments.attachment')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_images', to='base_feature_app.globalcolor')),
                ('peluch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_images', to='base_feature_app.peluch')),
            ],
            options={
                'ordering': ['color__sort_order', 'display_order'],
            },
        ),
    ]
