# Generated by Django 6.0.4 on 2026-04-22 01:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_feature_app', '0007_add_peluch_color_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peluch',
            options={'ordering': ['display_order', '-is_featured', '-created_at']},
        ),
        migrations.AddField(
            model_name='peluch',
            name='discount_pct',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='peluch',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=100),
        ),
    ]
