# Generated by Django 6.0.4 on 2026-04-27 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_feature_app', '0009_category_image_category_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontent',
            name='key',
            field=models.CharField(choices=[('faq', 'Preguntas frecuentes'), ('history', 'Historia de Peluchelandia'), ('terms', 'Términos y condiciones'), ('welcome_text', 'Texto de bienvenida'), ('contact_info', 'Información de contacto'), ('promo_banner', 'Cinta de promoción'), ('hero_image', 'Imagen del hero')], max_length=30, unique=True),
        ),
    ]
