# Generated by Django 6.0.2 on 2026-05-07 17:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_feature_app', '0010_alter_sitecontent_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount_paid_now',
            field=models.PositiveIntegerField(default=0, help_text='Monto que pagó el cliente al confirmar el pedido (lo que va a Wompi).'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.PositiveIntegerField(default=0, help_text='Descuento aplicado al elegir pago completo (snapshot).'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(choices=[('deposit', 'Anticipo (contraentrega)'), ('full', 'Pago completo')], default='deposit', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_amount',
            field=models.PositiveIntegerField(default=0, help_text='Costo de envío sumado de los items del pedido (snapshot).'),
        ),
        migrations.AddField(
            model_name='peluch',
            name='deposit_percentage',
            field=models.PositiveSmallIntegerField(default=50, help_text='% del precio que cobra como anticipo para pago contraentrega.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='peluch',
            name='free_shipping',
            field=models.BooleanField(default=False, help_text='Si está activo, este peluche no aporta costo de envío al carrito.'),
        ),
        migrations.AddField(
            model_name='peluch',
            name='full_payment_discount_pct',
            field=models.PositiveSmallIntegerField(default=0, help_text='% de descuento si el cliente paga el total por adelantado.', validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='peluch',
            name='shipping_cost',
            field=models.PositiveIntegerField(default=0, help_text='Costo de envío en COP (entero). Se ignora si free_shipping=True.'),
        ),
    ]
