import type { Blog, CartItem, Peluch } from '../types'

export const mockPeluches: Peluch[] = [
  {
    id: 1,
    title: 'Osito Coral',
    slug: 'osito-coral',
    category_name: 'Osito clásico',
    category_slug: 'osito-clasico',
    lead_description: 'El oseznito más querido',
    badge: 'bestseller',
    is_featured: true,
    min_price: 85000,
    available_colors: [{ id: 1, name: 'Rosa Coral', slug: 'rosa-coral', hex_code: '#D4848A', sort_order: 1 }],
    gallery_urls: ['http://example.com/image1.jpg'],
    average_rating: 4.9,
    review_count: 184,
    has_huella: true,
    has_corazon: false,
    has_audio: false,
  },
  {
    id: 2,
    title: 'Conejito Lucía',
    slug: 'conejito-lucia',
    category_name: 'Conejito',
    category_slug: 'conejito',
    lead_description: 'Una conejita adorable',
    badge: 'new',
    is_featured: false,
    min_price: 92000,
    available_colors: [{ id: 2, name: 'Rosa Pastel', slug: 'rosa-pastel', hex_code: '#FFD4D4', sort_order: 2 }],
    gallery_urls: ['http://example.com/image2.jpg'],
    average_rating: 4.7,
    review_count: 42,
    has_huella: false,
    has_corazon: true,
    has_audio: false,
  },
  {
    id: 3,
    title: 'Zorro Amiguito',
    slug: 'zorro-amiguito',
    category_name: 'Amigo del bosque',
    category_slug: 'amigo-del-bosque',
    lead_description: 'Un zorro travieso',
    badge: 'none',
    is_featured: false,
    min_price: 98000,
    available_colors: [],
    gallery_urls: ['http://example.com/image3.jpg'],
    average_rating: 4.5,
    review_count: 20,
    has_huella: false,
    has_corazon: false,
    has_audio: true,
  },
]

export const mockCartItems: CartItem[] = [
  {
    peluch_id: 1,
    peluch_slug: 'osito-coral',
    title: 'Osito Coral',
    size_id: 2,
    size_label: 'Mediano',
    color_id: 1,
    color_name: 'Rosa Coral',
    color_hex: '#D4848A',
    unit_price: 128000,
    personalization_cost: 0,
    quantity: 2,
    gallery_urls: ['http://example.com/image1.jpg'],
    has_huella: false,
    huella_type: '',
    huella_text: '',
    huella_media_id: null,
    has_corazon: false,
    corazon_phrase: '',
    has_audio: false,
    audio_media_id: null,
  },
  {
    peluch_id: 2,
    peluch_slug: 'conejito-lucia',
    title: 'Conejito Lucía',
    size_id: 1,
    size_label: 'Pequeño',
    color_id: 2,
    color_name: 'Rosa Pastel',
    color_hex: '#FFD4D4',
    unit_price: 92000,
    personalization_cost: 0,
    quantity: 1,
    gallery_urls: ['http://example.com/image2.jpg'],
    has_huella: false,
    huella_type: '',
    huella_text: '',
    huella_media_id: null,
    has_corazon: false,
    corazon_phrase: '',
    has_audio: false,
    audio_media_id: null,
  },
]

export const mockBlogs: Blog[] = [
  {
    id: 1,
    title: 'How to Choose the Perfect Peluch',
    description: 'A comprehensive guide',
    category: 'Tips',
    image_url: 'http://example.com/blog1.jpg',
  },
  {
    id: 2,
    title: 'The Art of Peluch Making',
    description: 'Learn about the craft',
    category: 'Education',
    image_url: 'http://example.com/blog2.jpg',
  },
  {
    id: 3,
    title: 'Top Peluches 2026',
    description: 'Trending picks',
    category: 'Trends',
    image_url: 'http://example.com/blog3.jpg',
  },
]

export const mockPeluch: Peluch = mockPeluches[0]

// Legacy aliases for tests that haven't migrated yet
export const mockProducts = mockPeluches
export const mockProduct = mockPeluch
